### ISSUE TITLE
Bot Registration

### ISSUE THREAD

**Issue by dinosaw** [raymestalez/mastodon-hnbot#1]
Would you mind elaborating on the following from the README?

> Create an account for the bot. For convenience you can use youremail+hnbot@gmail.com, to avoid registering a separate email.

I don't quite understand. Does that mean if I just append a `+hnbot` to an email address, the account doesn't need to be confirmed? I'm just not understanding the logic.

Edit: I would test it, but since you can't remove users yet I didn't want to clutter my instance.

**Comment by lumenwrites** [comment]
It is just a general gmail feature. You can add +anything at the end of your email address, and it will treat it as the same email.

**Comment by dinosaw** [comment]
Mind. Blown.

Thank you for this app and this Gmail tip! No clue how I was not aware of this!
