### ISSUE TITLE
ImportError: No Module named 'Mastodon'

### ISSUE THREAD

**Issue by c-hew** [raymestalez/mastodon-hnbot#3]
Having this issue...
```
Traceback (most recent call last):
  File "./hnbot.py", line 3, in <module>
    from mastodon import Mastodon
ImportError: No module named 'mastodon'

```

**Comment by pokrface** [comment]
Same exact problem. This is when running the initial setup command:

```
python3 ./hnbot.py "youremail@example.com" "yourpassword" "https://instancename.com"
```

This results in the same error that @owlg mentioned above:

```
Traceback (most recent call last):
  File "./hnbot.py", line 3, in <module>
    from mastodon import Mastodon
ImportError: No module named 'mastodon'
```

Any assistance would be appreciated.

**Comment by lumenwrites** [comment]
```
pip3 install Mastodon.py
```

**Comment by pokrface** [comment]
Thanks, @raymestalez—that's fixed it!

**Comment by SamerAl-khateeb** [comment]
This is still an ongoing error?! 
I installed it and I can see the **mastodon** folder inside **site-packages** and the folder contains **Mastodon.py** and **streaming.py** however, I am still getting `ImportError: cannot import name 'Mastodon' from 'mastodon' `any idea how to fix this?

also, when I try running `pip3 install Mastodon.py` I get this message `Requirement already satisfied: chardet<4,>=3.0.2 in ....`

**Comment by robmiracle** [comment]
This is still an issue.  Using Python 3.7 on macOS Ventura:

```
MacBook-Pro:Balancer rmiracle$ python3 -V
Python 3.7.3
MacBook-Pro:Balancer rmiracle$
```

It is installed:

```
MacBook-Pro:Balancer rmiracle$ pip3 show Mastodon.py
Name: Mastodon.py
Version: 1.8.0
Summary: Python wrapper for the Mastodon API
Home-page: https://github.com/halcy/Mastodon.py
Author: Lorenz Diener
Author-email: lorenzd+mastodonpypypi@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: python-dateutil, requests, decorator, blurhash, python-magic, six
Required-by: 
MacBook-Pro:Balancer rmiracle$ 
```

The Python source code:

`from mastodon import Mastodon`

The error:

```
MacBook-Pro:Balancer rmiracle$ python3 balancer.py
Traceback (most recent call last):
  File "balancer.py", line 3, in <module>
    from mastodon import Mastodon
ModuleNotFoundError: No module named 'mastodon'
MacBook-Pro:Balancer rmiracle$ 
```

I also tried:

`from Mastodon import Mastodon`

and

`from Mastodon.py import Mastodon`

Now if I do a pip3 list, this library is the only one with a .py extension in the name and the only one that is capitalized:

```
MacBook-Pro:Balancer rmiracle$ pip3 list
Package          Version   
---------------- ----------
blurhash         1.1.4     
certifi          2019.3.9  
chardet          3.0.4     
decorator        5.1.1     
dice             3.1.0     
docopt           0.6.2     
idna             2.8       
Mastodon.py      1.8.0     
mercurial        5.2       
pip              19.3.1    
pipenv           2018.11.26
protobuf         3.11.2    
pyparsing        2.4.7     
python-dateutil  2.8.2     
python-magic     0.4.27    
rbmwgtsite       1.4       
requests         2.22.0    
setuptools       41.6.0    
six              1.13.0    
urllib3          1.25.8    
virtualenv       16.6.0    
virtualenv-clone 0.5.3     
wheel            0.33.6    
MacBook-Pro:Balancer rmiracle$ 
```

So it's clearly installed yet python3 doesn't want to find it. 

Any thoughts?

**Comment by SamerAl-khateeb** [comment]
I have a working code in this repo `https://github.com/SamerAl-khateeb/MastodonDataCollection.git` incase someone is interested. 
Try this:
Open terminal or cmd:
Mac users type:
`python3 -m pip install Mastodon.py -–user`
Windows users type:
 `py -m pip install Mastodon.py -–user`

then this `from mastodon import Mastodon` worked for me!

If you use the code in the repo provided (or modified version of it), please cite this article: 
Al-khateeb, Samer. (2022). Dapping into the Fediverse: Analyzing What’s Trending on Mastodon Social. In: Thomson, R., Dancy, C., Pyke, A. (eds) Social, Cultural, and Behavioral Modeling. SBP-BRiMS 2022. Lecture Notes in Computer Science, vol 13558. Springer, Cham. https://doi.org/10.1007/978-3-031-17114-7_10
